name: campus_map
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.0.0  
  font_awesome_flutter: ^10.3.0 
  cupertino_icons: ^1.0.8
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_pdfview: ^1.3.4
  syncfusion_flutter_pdfviewer: ^28.1.35
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/pinpoint.png
    - assets/image/shadow.png
    - assets/image/MAP.png
    - assets/image/MISFL1.png
    - assets/image/MISFL2.png
    - assets/image/MISFL3.png
    - assets/image/MISFL4.png
    - assets/image/MISFL5.png
    - assets/image/cafa.png
    - assets/image/cas.png
    - assets/image/cba.png
    - assets/image/ccje.png
    - assets/image/ccs.png
    - assets/image/ced.png
    - assets/image/cen.png
    - assets/image/chtm.png
    - assets/image/cit.png
    - assets/svg/1.svg
    - assets/svg/2.svg
    - assets/svg/3.svg
    - assets/svg/4.svg
    - assets/svg/5.svg
    - assets/svg/6.svg
    
 
    
  fonts:
    - family: Arquitectura
      fonts:
        - asset: assets/font/Arquitectura Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf

    

